import fs from "fs/promises";
import path from "path";
import { createHash } from "crypto";

export type DocumentVerificationResult = {
  valid: boolean;
  score: number;
  checks: { name: string; passed: boolean; detail: string }[];
  fileHash: string;
};

const AI_SIGNATURES = [
  "midjourney",
  "dall-e",
  "dalle",
  "stable diffusion",
  "openai",
  "generated by ai",
  "this image was created",
];

const EDITING_SIGNATURES = [
  "photoshop",
  "adobe",
  "gimp",
  "canva",
  "lightroom",
  "snapseed",
  "picsart",
];

function detectMime(buffer: Buffer): string | null {
  if (buffer.slice(0, 4).toString() === "%PDF") return "application/pdf";
  if (buffer[0] === 0xff && buffer[1] === 0xd8) return "image/jpeg";
  if (buffer.slice(0, 8).toString("hex") === "89504e470d0a1a0a") return "image/png";
  if (buffer.slice(0, 4).toString() === "RIFF" && buffer.slice(8, 12).toString() === "WEBP") {
    return "image/webp";
  }
  // Word .doc (Compound File Binary Format)
  if (buffer.slice(0, 8).toString("hex") === "d0cf11e0a1b11ae1") return "application/msword";
  // Word .docx (Office Open XML - Zip-based)
  if (buffer.slice(0, 4).toString("hex") === "504b0304") {
    // Check if it's actually a docx by looking for [Content_Types].xml or word/
    const content = buffer.toString("latin1");
    if (content.includes("word/") || content.includes("[Content_Types].xml")) {
      return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    }
    return "application/zip";
  }
  return null;
}

function readJpegDimensions(buffer: Buffer): { width: number; height: number } | null {
  let offset = 2;
  while (offset < buffer.length) {
    if (buffer[offset] !== 0xff) break;
    const marker = buffer[offset + 1];
    const length = buffer.readUInt16BE(offset + 2);
    if (marker === 0xc0 || marker === 0xc2) {
      return {
        height: buffer.readUInt16BE(offset + 5),
        width: buffer.readUInt16BE(offset + 7),
      };
    }
    offset += 2 + length;
  }
  return null;
}

function scanBufferForSignatures(buffer: Buffer, signatures: string[]): string[] {
  const text = buffer.toString("latin1").toLowerCase();
  return signatures.filter((sig) => text.includes(sig));
}

export async function verifyDocumentFromUrl(
  publicUrl: string
): Promise<DocumentVerificationResult> {
  const checks: DocumentVerificationResult["checks"] = [];
  const relativePath = publicUrl.startsWith("/") ? publicUrl.slice(1) : publicUrl;
  const filePath = path.join(process.cwd(), "public", relativePath);

  let buffer: Buffer;
  try {
    buffer = await fs.readFile(filePath);
  } catch {
    return {
      valid: false,
      score: 0,
      checks: [{ name: "file_exists", passed: false, detail: "File dokumen tidak ditemukan" }],
      fileHash: "",
    };
  }

  const fileHash = createHash("sha256").update(buffer).digest("hex");

  const mime = detectMime(buffer);
  const isWord = mime === "application/msword" || mime === "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
  const formatOk = mime === "application/pdf" || mime?.startsWith("image/") || isWord;
  checks.push({
    name: "format",
    passed: !!formatOk,
    detail: formatOk ? `Format valid (${mime})` : "Format harus PDF, Word, atau Gambar (JPG/PNG)",
  });

  // Stricter Size check
  const sizeOk = buffer.length >= 50_000; // Increased from 30k
  checks.push({
    name: "size",
    passed: sizeOk,
    detail: sizeOk
      ? `Ukuran file memadai (${Math.round(buffer.length / 1024)} KB)`
      : "File terlalu kecil — kemungkinan dokumen kosong atau tidak valid",
  });

  // Check for suspicious patterns (Screenshots)
  const isScreenshot = scanBufferForSignatures(buffer, ["screenshot", "screen shot", "captura de pantalla"]).length > 0;
  checks.push({
    name: "integrity",
    passed: !isScreenshot,
    detail: !isScreenshot ? "Bukan merupakan tangkapan layar (screenshot)" : "Terdeteksi sebagai screenshot, harap unggah dokumen asli",
  });

  // Basic Malware/Suspicious Content Scan
  const MALICIOUS_PATTERNS = [
    "<script", "javascript:", "eval(", "onload=", "onerror=", 
    "/JS", "/JavaScript", "/AA", "/OpenAction", // PDF specific malicious keys
    "powershell", "cmd.exe", ".exe", ".bat", ".vbs", ".sh"
  ];
  const malwareHits = scanBufferForSignatures(buffer, MALICIOUS_PATTERNS);
  const securityOk = malwareHits.length === 0;
  checks.push({
    name: "security_scan",
    passed: securityOk,
    detail: securityOk 
      ? "Tidak terdeteksi konten aktif atau skrip berbahaya" 
      : `Terdeteksi konten mencurigakan: ${malwareHits.slice(0, 3).join(", ")}`,
  });

  const aiHits = scanBufferForSignatures(buffer, AI_SIGNATURES);
  const aiOk = aiHits.length === 0;
  checks.push({
    name: "ai_detection",
    passed: aiOk,
    detail: aiOk ? "Tidak terdeteksi tanda AI-generated" : `Terdeteksi: ${aiHits.join(", ")}`,
  });

  const editHits = scanBufferForSignatures(buffer, EDITING_SIGNATURES);
  const editOk = editHits.length === 0;
  checks.push({
    name: "editing_detection",
    passed: editOk,
    detail: editOk
      ? "Tidak terdeteksi metadata editor grafis"
      : `Terindikasi edit: ${editHits.join(", ")}`,
  });

  if (mime?.startsWith("image/")) {
    const dims = readJpegDimensions(buffer);
    if (dims) {
      const resOk = dims.width >= 600 && dims.height >= 400;
      checks.push({
        name: "resolution",
        passed: resOk,
        detail: resOk
          ? `Resolusi ${dims.width}x${dims.height}px — memadai`
          : `Resolusi ${dims.width}x${dims.height}px — terlalu rendah untuk dokumen resmi`,
      });
    }
  }

  if (mime === "application/pdf") {
    const pdfOk = buffer.includes(Buffer.from("%%EOF"));
    checks.push({
      name: "pdf_integrity",
      passed: pdfOk,
      detail: pdfOk ? "Struktur PDF utuh" : "Struktur PDF tidak valid",
    });
  }

  const passedCount = checks.filter((c) => c.passed).length;
  const score = Math.round((passedCount / checks.length) * 100);
  const criticalFailed = checks.some(
    (c) => !c.passed && ["format", "ai_detection", "file_exists", "integrity", "security_scan"].includes(c.name)
  );
  const valid = !criticalFailed && score >= 80; // Increased threshold from 70 to 80

  return { valid, score, checks, fileHash };
}
